### ISSUE TITLE
BAD REQUEST

### ISSUE THREAD

**Issue by Coder-of-Bots** [TannerReynolds/Translation-Bot#25]
{ Error
    at C:\Users\me\Desktop\Translation-Bot\node_modules\google-translate-api\index.js:105:17
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'BAD_REQUEST' }

Getting this error when :t <lang> <message> is being executed

**Comment by urPlaceOrMine** [comment]
Hi --
a couple of questions for you. 

What operating system are you running it under?
What is your version of Node.js?
can you show your the config.json and enter 00000000 for the discord ids and token?

ty upm (urPlaceOrMine)

**Comment by urPlaceOrMine** [comment]
One additional thought.  This is NOT an issue with this project.  This error is casually discussed in the Google-Translate-Api github form.  For me the BOT works really well for casual use.  We have 148 users on our Discord and we get a BAD_REQUEST (503) about once a week. i stop the BOT for 24 hours of (NO activity ) it seems to fix it and less traffic..

**Comment by kokkie20** [comment]
I got same issue and just started the bot up for first time :(
Any idea?

**Comment by urPlaceOrMine** [comment]
When I saw the error I was still able to use the help function in Discord using the ":t help" command. 
I also notice I had loop my setting up the channel translator that caused the error BAD_REQUEST.  
can you change line 107 in the node_modules\google-translate-api\index.js to this to see if you are getting error 503?
               e.code = err.statusCode;

**Comment by MFOCD** [comment]
I had the same issue, did what you said, and got this
at C:\Users\amfoc\OneDrive\Documents\Translation-Bot-master\node_modules\google-translate-api\index.js:105:17
    at process.internalTickCallback (internal/process/next_tick.js:77:7) code: 403

**Comment by urPlaceOrMine** [comment]
Did this ever work for you?
 comments.   
1) try this forked version of the google-translate-api.  My translator has been working very reliably since I started using it.  https://github.com/matheuss/google-translate-api/issues/79#issuecomment-427841889
2) With the above API I am also able to run the translator on the new Raspberry Pii and linux.
3) Here is a descent Google translator very similar to this one.  The Project is simply asking for donations to help keep it free. https://discordbots.org/bot/471542070817849355.  

Please follow up here with your solution to help everyone.

UPoM
